name: "myapp-gha-workflow"
on: push

env:
  JFROG_CLI_BUILD_PROJECT: "shire"
  JFROG_CLI_BUILD_NAME: "myapp-gha-workflow"
  JFROG_CLI_BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}
      - name: Check-JFrog-CLI-and-Artifactory-Server
        run: |
          # Check version of Artifactory
          jfrog --version
          # Check Artifactory Server connectiviy with a CLI Ping
          jfrog rt ping 

      - name: Zip-files
        uses: papeloto/action-zip@v1
        with:
          files: src/
          dest: myapp.zip
          
      - name: Publish-Build-Info-to-Artifactory
        run: |
          # Set Artifactory Project scope
          echo "Publish build: Project [$JFROG_CLI_BUILD_PROJECT] , Build Name [$JFROG_CLI_BUILD_NAME] , Build Number [$JFROG_CLI_BUILD_NUMBER] "
          ls -la 
          # Collect environment variables for the build
          jfrog rt bce
          # Collect VCS details from git and add them to the build
          jfrog rt bag
          # Publish build info
          jfrog rt bp          

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Tests
        run: |
          # Run tests
          echo "Your tests go here"

  promote-to-non-prod:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}
      - name: Promote Build
        run: |
          echo "Promote build: Project [$JFROG_CLI_BUILD_PROJECT] , Build Name [$JFROG_CLI_BUILD_NAME] , Build Number [$JFROG_CLI_BUILD_NUMBER] "
          # Check version of Artifactory
          jfrog --version
